version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile-php
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./source:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
